### ISSUE TITLE
Replace Bash ~and Python~ scripts with Rust

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3349]
We have a bunch of Python scripts in our repository for CI stuff, linting, etc.

We would like to replace them all with Rust, perhaps using something like [`xtask`](https://github.com/matklad/cargo-xtask).

Some things we need to make sure of:

* The helper scripts should still be single-file (not need a `Cargo.toml` per script).See e.g. https://github.com/rust-lang/rfcs/pull/3424
* Each file should have very light dependencies and compile quickly (avoid e.g. `clap`)
* Work hard on keeping the code simple and terse

Related issues:
* https://github.com/rerun-io/rerun/issues/2200
* https://github.com/rerun-io/rerun/issues/2174
* https://github.com/rerun-io/rerun/issues/5889

---

If we replace `lint.py` with Rust, we should consider using `ast_grep_core` of https://github.com/ast-grep/ast-grep

**Comment by emilk** [comment]
True, but python still requires a separate `pip install -r …` step at the moment which `cargo run` doesn't, but that may be something `pixi` will solve for us

**Comment by abey79** [comment]
I'd argue our ubiquitous use of `requirements.txt` is a bit the issue there. We should put everything in `pyproject.toml` for a centralised, single source of truth, using this pattern:

```toml
[project.optional-dependencies]
tests = ["pytest==7.1.2"] # we somehow have this here already, not sure we actually use it
dev = [
    # .... put everything we need
]
docs = [
    # ... if we feel necessary, we can sub-categorise
]
```

Then, `pip install -e ".[dev]"` should do the trick.

The disadvantage is that these "extra" are published/visible to pypi. Poetry includes another mechanism ([optional groups](https://python-poetry.org/docs/managing-dependencies/#optional-groups)) that would be a better fit.
