### ISSUE TITLE
Structured object view

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#394]
Create a new type of SpaceView that views our object hiearchy in a terse, pretty-way:

```
object:
  field: 32
  name: "Peter"
  image: [miniature image here]
  child:
    more: true
    stuff: [tensor]
```

etc.

It's a mostly-text snapshot of all your data at the current time, with links to each object and some small inline previews of images, colors, etc.

This is similar to what we currently show in the selection panel, but should be recursive, and have its dedicated view.

As you scroll the time, you would see the field values change.
