### ISSUE TITLE
The current link checking strategy is _very_ error prone

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#7887]
I've broken dozens of links with my recent doc changes without knowing.

The only reason I noticed the damage was because `nightly` failed when everything else somehow passes.

Turns out, the link checking job does run everywhere, but always reports success unless it's running on nightly:
```yaml
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          fail: ${{ inputs.CHANNEL == 'nightly' }}
```

That's not very helpful as-is.
