### ISSUE TITLE
`serve_web` followed by `disconnect` outside of main thread causes 100% CPU usage

### ISSUE THREAD

**Issue by goktug97** [rerun-io/rerun#8806]
**Description**
`serve_web` followed by `disconnect` in an asyncio executor causes 100% CPU usage. `disconnect` closes the websocket as expected. This issue was encountered while running `serve_web` in a FastAPI request and can be reproduced in an asyncio context.

- Running `rec.inner.flush()` before `disconnect` didn't help.
- Sleeping for some time before `disconnect` to ensure all data is streamed also didn't resolve the issue.

**To Reproduce**
- Minimal Example:
```python
from uuid import uuid4
import rerun as rr
import asyncio

async def stream():
    rec = rr.new_recording(application_id=str(uuid4()), recording_id=uuid4())
    rr.serve_web(open_browser=False, web_port=0, ws_port=0, recording=rec)
    rec.disconnect()


async def main():
    await stream()

    while True:
        print("Running")
        await asyncio.sleep(1)


asyncio.run(main())
```

- Minimal Example with FastAPI:
```python
from uuid import uuid4

from fastapi import FastAPI
import rerun as rr

app = FastAPI()

@app.post("/api/stream")
async def stream():
    rec = rr.new_recording(application_id=str(uuid4()), recording_id=uuid4())
    rr.serve_web(open_browser=False, web_port=0, ws_port=0, recording=rec)
    rec.disconnect()
```

```toml
[project]
name = "2025-01-rerun-fastapi-issue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.7",
    "rerun-sdk>=0.21.0",
]
```

```bash
fastapi run main.py
curl -X POST http://localhost:8000/api/stream
```

**Expected behavior**
Calling disconnect should not leave a process running that consumes 100% of CPU resources.

**Desktop:**
 - OS: NixOS 24.04

**Rerun version**
0.21.0
